-- MySQL Script generated by MySQL Workbench
-- Sun Dec 10 16:20:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `patronymic` VARCHAR(30) NULL,
  `cluster_name` VARCHAR(20) NULL,
  `discount` FLOAT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `id_client_UNIQUE` (`id_client` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cards` (
  `id_card` INT NOT NULL,
  `card_number` VARCHAR(16) NOT NULL,
  `username` VARCHAR(60) NOT NULL,
  `validity` VARCHAR(5) NOT NULL,
  `cvv` VARCHAR(3) NOT NULL,
  `clients_id_client` INT NOT NULL,
  PRIMARY KEY (`id_card`),
  UNIQUE INDEX `id_card_UNIQUE` (`id_card` ASC) ,
  UNIQUE INDEX `card_number_UNIQUE` (`card_number` ASC) ,
  INDEX `fk_cards_clients_idx` (`clients_id_client` ASC) ,
  CONSTRAINT `fk_cards_clients`
    FOREIGN KEY (`clients_id_client`)
    REFERENCES `mydb`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`points` (
  `id_point` INT NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `house` VARCHAR(50) NOT NULL,
  `open_time` TIME NOT NULL,
  `close_time` TIME NOT NULL,
  PRIMARY KEY (`id_point`),
  UNIQUE INDEX `id_point_UNIQUE` (`id_point` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `points_id_point` INT NOT NULL,
  `cards_id_card` INT NOT NULL,
  `clients_id_client` INT NOT NULL,
  `clients_id_admin` INT NOT NULL,
  PRIMARY KEY (`id_order`, `cards_id_card`, `points_id_point`),
  UNIQUE INDEX `id_order_UNIQUE` (`id_order` ASC) ,
  INDEX `fk_orders_points1_idx` (`points_id_point` ASC) ,
  INDEX `fk_orders_cards1_idx` (`cards_id_card` ASC) ,
  INDEX `fk_orders_clients1_idx` (`clients_id_client` ASC) ,
  INDEX `fk_orders_clients2_idx` (`clients_id_admin` ASC) ,
  CONSTRAINT `fk_orders_points1`
    FOREIGN KEY (`points_id_point`)
    REFERENCES `mydb`.`points` (`id_point`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_cards1`
    FOREIGN KEY (`cards_id_card`)
    REFERENCES `mydb`.`cards` (`id_card`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_clients1`
    FOREIGN KEY (`clients_id_client`)
    REFERENCES `mydb`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_clients2`
    FOREIGN KEY (`clients_id_admin`)
    REFERENCES `mydb`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materials` (
  `id_material` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id_material`),
  UNIQUE INDEX `id_material_UNIQUE` (`id_material` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pickups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pickups` (
  `id_pickup` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `producer` VARCHAR(20) NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id_pickup`),
  UNIQUE INDEX `id_pickup_UNIQUE` (`id_pickup` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`promotions` (
  `percent_promo` INT NOT NULL,
  `condition` VARCHAR(100) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `id_promotion` INT NOT NULL,
  PRIMARY KEY (`id_promotion`),
  UNIQUE INDEX `id_promotion_UNIQUE` (`id_promotion` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `vendor_code` INT NOT NULL,
  `name_of_product` VARCHAR(40) NOT NULL,
  `price` INT NOT NULL,
  `producer` VARCHAR(40) NOT NULL,
  `number_strings` INT NOT NULL,
  `number_frets` INT NOT NULL,
  `issue_year` INT NOT NULL,
  `materials_id_body` INT NOT NULL,
  `materials_id_vulture` INT NOT NULL,
  `pickups_id_pickup` INT NOT NULL,
  ` promotions_id_promotion` INT NOT NULL,
  PRIMARY KEY (`vendor_code`, `materials_id_body`, `pickups_id_pickup`, `materials_id_vulture`),
  UNIQUE INDEX `vendor_code_UNIQUE` (`vendor_code` ASC) ,
  INDEX `fk_products_materials1_idx` (`materials_id_body` ASC) ,
  INDEX `fk_products_materials2_idx` (`materials_id_vulture` ASC) ,
  INDEX `fk_products_pickups1_idx` (`pickups_id_pickup` ASC) ,
  INDEX `fk_products_ promotions1_idx` (` promotions_id_promotion` ASC) ,
  CONSTRAINT `fk_products_materials1`
    FOREIGN KEY (`materials_id_body`)
    REFERENCES `mydb`.`materials` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_materials2`
    FOREIGN KEY (`materials_id_vulture`)
    REFERENCES `mydb`.`materials` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_pickups1`
    FOREIGN KEY (`pickups_id_pickup`)
    REFERENCES `mydb`.`pickups` (`id_pickup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_ promotions1`
    FOREIGN KEY (` promotions_id_promotion`)
    REFERENCES `mydb`.` promotions` (`id_promotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compounds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compounds` (
  `quantity` INT NOT NULL,
  `products_vendor_code` INT NOT NULL,
  `orders_id_order` INT NOT NULL,
  PRIMARY KEY (`products_vendor_code`, `orders_id_order`),
  INDEX `fk_compounds_orders1_idx` (`orders_id_order` ASC) ,
  CONSTRAINT `fk_compounds_products1`
    FOREIGN KEY (`products_vendor_code`)
    REFERENCES `mydb`.`products` (`vendor_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compounds_orders1`
    FOREIGN KEY (`orders_id_order`)
    REFERENCES `mydb`.`orders` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personals` (
  `login` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `clients_id_client` INT NOT NULL,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) ,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  PRIMARY KEY (`clients_id_client`),
  CONSTRAINT `fk_personals_clients1`
    FOREIGN KEY (`clients_id_client`)
    REFERENCES `mydb`.`clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
